### ISSUE TITLE
Switching language doesn't work.

### ISSUE THREAD

**Issue by dvdmchl** [dvdmchl/JETA-electronjs#1]

**Comment by awe-s0me** [comment]
Confirmed.

**Comment by awe-s0me** [comment]
When CS language is selected, after Refresh (Ctrl+R), the content of index.html is back in EN, although menu stays in CS.

**Comment by awe-s0me** [comment]
New Game Definition (Ctrl+N) creates a new window with En texts only, regardless of chosen language.
